openapi: 3.1.0
info:
  title: Similar Products API
  description: API to obtain similar products given a product ID
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /product/{productId}/similar:
    get:
      tags:
        - Products
      summary: Get similar products
      description: Returns a list of products that are similar to the specified product ID
      operationId: getSimilarProducts
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to find similar items for
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
        - availability
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: Unique identifier of the product
        name:
          type: string
          example: "T-Shirt"
          description: Name of the product
        price:
          type: number
          format: float
          example: 19.99
          description: Price of the product
        availability:
          type: boolean
          example: true
          description: Availability status of the product
    
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 404
        message: Product not found
